config/routes.rb
Rails.application.routes.default_url_options[:host] = ENV["host"]
Rails.application.routes.draw do
  ##in future
  telegram_webhook TelegramWebhooksController
  resources :jobs
  get 'approve_job/:id', to: 'jobs#approve', as: :approve
  get 'sitemap', to: 'index#sitemap', as: :sitemap

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :properties
  #devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'index#index'
  get 'search', to: 'index#main_search'

  get '*path', to: 'errors#error_404', via: :all

end

app/models/job.rb
# frozen_string_literal: true
require 'date'

class Job < ApplicationRecord

  enum job_type: { full_time: 0, part_time: 1, casual: 2, permanent: 3 }
  enum remote: { no: false, yes: true }
  include AASM

  validates :title, presence: { message: :title_empty }
  validates :location, presence: { message: :location_empty }
  validates :description, length: { minimum: 100, message: :description_is_short }

  aasm do # default column: aasm_state
    state :new, initial: true
    state :approved
    state :rejected

    event :approve do
      transitions from: :new, to: :approved
    end

    event :reject do
      transitions from: :new, to: :rejected
    end

    event :to_new do
      transitions from: :approved, to: :new
    end
  end

  def approve;  end

  def to_new;  end

  def reject; end

  def date_posted
    updated_at.to_date()
  end

  def to_hash
    {title: title,
     company_name: company_name,
     remote: remote,
     location: location,
     description: description,
     salary_min: salary_min,
     salary_max: salary_max,
     job_type: job_type,
     contact: contact}
  end

  def to_telegram
    tag_remote = remote=='no' ? I18n.t('show.job.remote') : Addition.to_hashtag(I18n.t('show.job.remote'))
    text = ''
    text += "<strong>#{title}</strong>\n"
    text += "<strong>#{I18n.t('show.job.company')}:</strong> #{company_name}\n"
    text += "<strong>#{I18n.t('show.job.location')}:</strong> #{Addition.to_hashtag(location)}\n"
    #text += "<strong>#{tag_remote}:</strong> #{I18n.t("job.remote.#{remote}")}\n"
    text += "<strong>#{I18n.t('show.job.job_type')}:</strong> #{Addition.to_hashtag(I18n.t("job.job_type.#{job_type}"))}\n"
    text += "<strong>#{I18n.t('show.job.salary')}:</strong> #{salary(true)}\n" if salary
    text += "<strong>#{I18n.t('show.job.description')}</strong>\n"
    text += "#{description_text(400)}...\n"
    text
  end

  def salary(tag = false)
    local_tag = tag ? 'salary_tag' : 'salary'
    min = salary_min || 0
    max = salary_max || 0
    return I18n.t(local_tag, salary: min) if min != 0 and max == 0
    return I18n.t(local_tag, salary: max) if min == 0 and max != 0
    return nil if min == 0 and max == 0
    "#{I18n.t(local_tag, salary: min)} - #{I18n.t(local_tag, salary: max)}"
  end

  def self.search(search_params)
    query = search_params.to_query
    logger.debug("Query:: #{query}")
    params = search_params.to_h
    logger.debug("Params:: #{params.to_s}")
    return self.all if query.blank?
    mode = "ARRAY['phrase', 'plain', 'none']"
    select(:id, :title, :company_name, :remote, :location, :description, :tags, :updated_at,
           :salary_min, :salary_max, :job_type, :contact,
           "user_rank(fts, '#{params[:search_key]}', '#{params[:search_key]}', #{mode}) AS \"rank\"").where(query, params)
  end

  def description_text( truncate=nil)
    #description.gsub(/<strong>|<\/strong>|<span>|<\/span>|<\/div>|<ul>|<\/ul>|<\/li>|<\/p>|<li>|<br>|<div>|<h1>|<h2>|<h3>|<h4>|<b>|<\/h1>|<\/h2>|<\/h3>|<\/h4>|<\/b>|<p>/," ").squish
    if description
      arg = truncate.nil? ?  description : description[0..truncate*2]
      text = HtmlToPlainText.plain_text(arg).squish
      if truncate
        text = text.truncate(truncate, separator: ' ',omission: '')
      end
    end
  end

  def keywords(count_keys = 20, min_length_word = 4)
    if title
      array_keywords = [title] * 10
      array_keywords += [location] * 10
      if description
        desc = HtmlToPlainText.plain_text(description)
        desc = Addition.remote_frequent_keywords(desc)&.squish
        array_keywords += desc&.gsub(/[^[:word:]]/, ' ')&.downcase&.split(' ')
      end
      array_keywords.compact!
      index_hash = {}
      array_keywords.each do |word|
        if word.length > min_length_word
          index_hash[word] ? index_hash[word] += 1 : index_hash[word] = 1
        end
      end
      array_keywords = []
      index_hash.each do |key, value|
        array_keywords << { key => value }
      end
      array_keywords.sort { |x, y| y.values[0] <=> x.values[0] }[0..count_keys - 1].map { |t| t.keys.first }
    end
  end

  def title_text
    if title
      location.present? ? "#{location} | #{title}" : title
    end
  end


end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < InheritedResources::Base
  load_and_authorize_resource :job, only: %i[edit, update, destroy] #TODO, approve
  before_action :set_job, only: %i[edit update destroy approve]

  def new
    @job = Job.new
  end

  def edit; end

  def update
    respond_to do |format|
      if @job.new?
        if @job.update(job_params)
          format.html { redirect_to job_path, notice: t('edit.job.success') }
        else
          format.html { render :edit }
        end
      else
        format.html { redirect_to job_path, notice: t('edit.job.success') }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: t('destroy.job.success')  }
    end
  end

  def approve
    ApproveJob.call(object: @job)
    respond_to do |format|
      format.html { redirect_to job_path, notice: t('approve.job.success')  }
    end
  end

  def create
    @create_job = CreateJob.call(params: job_params)
    @job = @create_job.object
    respond_to do |format|
      if @create_job.success?
        SendMessage.call(text: job_url(@job), chat: :admin_chat_id)
        format.html { redirect_to @job, notice: t('posted.job.success') }
        format.json { render :show, status: :created, location: @create_job.object }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :company_name, :remote, :location, :salary_min, :salary_max,
                                :contact, :description, :job_type)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def contact_normalize(contact)
    if contact.host.nil?
      contact.host = 't.me'
      contact.scheme = 'https'
      contact.path = "/#{contact.path.gsub('@','')}"
    end
    contact
  end

  def contact_tag(job)
    if job&.contact&.present?
      link = contact_normalize( URI( job.contact ) )
      if link.host == 't.me'
        link_to t('show.job.apply_telegram'), link.to_s, class: 'btn  btn-primary', role: 'button'
      else
        link_to t('show.job.apply'), job.contact, class: 'btn  btn-primary', role: 'button'
      end
    end
  end

end

app/views/jobs/_form.html.slim
= form_with(model: job) do |form|
  - if job.errors.any?
    .row.mb-3.sdfds
      .col-12.text-danger
        .error_explanation
          p.small
            = pluralize(job.errors.count, "error")
            |&nbsp; #{t('posted.job.error.form')}:
          ul
            - job.errors.each do |error|
              li.small
                = error.full_message

  .row.mb-3
    .col-12
      = form.label :title, t('post.form.title_label'), class: 'form-label'
      = form.text_field :title, class: 'form-control', required: true,
              placeholder: t('post.form.title_placeholder')

  .row.mb-3
    .col-6
      = form.label :company_name, t('post.form.company_label'), class: 'form-label'
      = form.text_field :company_name, class: 'form-control', placeholder: t('post.form.company_placeholder')
    .col-6
      = form.label :location, t('post.form.location_label'), class: 'form-label'
      = form.text_field :location, class: 'form-control', required: true,
              placeholder: t('post.form.location_placeholder')

  .row.mb-3
    .col-6
      = form.label :job_type, t('post.form.job_type_label'), class: 'form-label'
      = form.collection_select :job_type,
              Job.job_types.map{ |a| [a.first,t("job.job_type.#{a.first}")] },
              :first, :second, {}, {class: 'form-select'}
    .col-6
      = form.label :remote, t('post.form.remote_label'),class: 'form-label'
      = form.collection_select :remote,
              Job.remotes.map { |a| [a.first, t("job.remote.#{a.first}")] },
              :first, :second, {}, { class: 'form-select' }
  .row.mb-3
    .col-6
      = form.label :salary_min, t('post.form.salary_min_label'), class: 'form-label'
      .input-group
        span.input-group-text
          = t('money')
        = form.text_field :salary_min,
                type: 'number', min: '1', step: 'any',
                class: 'form-control', placeholder: t('post.form.salary_min_placeholder')
    .col-6
      = form.label :salary_max, t('post.form.salary_max_label'), class: 'form-label'
      .input-group
        span.input-group-text
          = t('money')
        = form.text_field :salary_max,
                type: 'number', min: '1', step: 'any',
                class: 'form-control', placeholder: t('post.form.salary_max_placeholder')
  .row.mb-3
    .col-12
      = form.label :description, t('post.form.description_label'), class: 'form-label'
      small
        |&nbsp; #{t('post.form.description_min_size')}
      = form.text_area :description,  id: 'description_output', class: 'form-control',
              required: true,  rows: 10,  placeholder: t('post.form.description_placeholder')
      /#editor
      /form-control[input = 'desc_id'  required  rows = '10'  placeholder =t('post.form.description_placeholder')]

  .row.mb-3
    .col-12
      = form.label :contact, t('post.form.contact_label'), class: 'form-label'
      = form.text_field :contact, class: 'form-control',
              placeholder: t('post.form.contact_placeholder'), required: true
  .row.mb-3
    .col-12
      = form.submit t('post.form.submit'), class: 'btn btn-primary'

app/views/jobs/_job.html.slim
.card.mb-3
  .card-body
    h5
      strong
        = link_to job.title, job_path(job), class:'text-capitalize simple_text'
    div
      span.text-success.te
        = job.company_name
      span
        | &nbsp; - &nbsp;
      span.text-warning
        = job.location
    div
      span
        =t("job.job_type.#{job.job_type}")
      - if  job.remote == 'yes'
        span
          | &nbsp; - &nbsp; #{t('show.job.remote')}
    div
      = job.salary
    div
      = simple_format(job.description_text(400)+ '...')
    .small.text-info.mb-3
      = l( job.date_posted, format: :default )
    .d-grid.gap-2.d-md-flex.justify-content-md-end
      = contact_tag( job )
      = link_to t('show.job.more'), job_path(job), class: 'btn btn-light', role: 'button'

app/views/jobs/edit.html.slim
h1
  | Editing Job
= render 'form', job: @job
= link_to 'Show', @job
|  | 
= link_to 'Back', jobs_path

app/views/jobs/index.html.slim
p#notice
  = notice
h1
  | Jobs
table
  thead
    tr
      th
        | Title
      th
        | Company name
      th
        | String
      th
        | Company link
      th
        | Remote
      th
        | Type
      th
        | Location
      th
        | Salary
      th
        | Source
      th
        | Contract
      th[colspan="3"]
  tbody
    - @jobs.each do |job|
      tr
        td
          = job.title
        td
          = job.company_name
        td
          = job.string
        td
          = job.company_link
        td
          = job.remote
        td
          = job.type
        td
          = job.location
        td
          = job.salary
        td
          = job.source
        td
          = job.contract
        td
          = link_to 'Show', job
        td
          = link_to 'Edit', edit_job_path(job)
        td
          = link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Job', new_job_path

app/views/jobs/new.html.slim
.card
  .card-header.text-center
    h1
      = t('post.form.title_form')

  .card-body
    = render 'form', job: @job

app/views/jobs/show.html.slim
- content_for :title, @job&.title_text
- meta_tag "description",   @job&.description_text
- meta_tag "keywords", @job&.keywords.join(', ')
- cache @job
  .card
    .card-header.text-center
      h3.card-title
        = @job.title
    .card-body.compact
      h5.text-center
        strong
          = t('show.job.job_details')
      -if @job.company_name
        p
          strong
            |#{t('show.job.company')}: &nbsp;
          span.text-warning
            = @job.company_name
      p
        strong
          |#{t('show.job.location')}: &nbsp;
        span.text-success
          = @job.location
      p
        strong
          |#{t('show.job.remote')}: &nbsp;
        span
          = t("job.remote.#{@job.remote}")
      p
        strong
          |#{t('show.job.job_type')}: &nbsp;
        span
          = t("job.job_type.#{@job.job_type}")
      - unless @job.salary.nil?
        p
          strong
            |#{t('show.job.salary')}: &nbsp;
          span
            =@job.salary
      p
        strong
          | #{t('show.job.posted')}: &nbsp;
        span
          = l( @job.date_posted, format: :default )
    .card-body
      h5.text-center
        strong
          |#{t('show.job.description')}
      .card-text
        =simple_format(@job.description)
    .card-body
      .row
        .d-grid.gap-2.d-md-flex.justify-content-md-center
          =contact_tag(@job)
          - if can? :edit, @job and @job.new?
            = link_to t('show.job.edit'), edit_job_path(@job), class: 'btn btn-warning'
          - if  @job.new? #can? :approve, @job
            = link_to t('show.job.approve'), approve_path(@job), class: 'btn btn-success'
          - if can? :destroy, @job
            = link_to t('show.job.destroy'), job_path(@job), class: 'btn btn-danger', :method => :delete