config/routes.rb
Rails.application.routes.default_url_options[:host] = ENV["host"]
Rails.application.routes.draw do
  ##in future
  telegram_webhook TelegramWebhooksController
  resources :jobs
  get 'approve_job/:id', to: 'jobs#approve', as: :approve
  get 'sitemap', to: 'index#sitemap', as: :sitemap

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :properties
  #devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'index#index'
  get 'search', to: 'index#main_search'

  get '*path', to: 'errors#error_404', via: :all

end

app/models/property.rb
class Property < ApplicationRecord

  def self.find_prop( prop )
    self.where( "LOWER(:prop) = LOWER(code)", prop: prop )&.first.value
  end

  def self.locations
    JSON.parse( find_prop( :locations ) )
  end

end

app/controllers/properties_controller.rb
class PropertiesController < InheritedResources::Base

  private

    def property_params
      params.require(:property).permit(:code, :value, :description)
    end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Value</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.code %></td>
        <td><%= property.value %></td>
        <td><%= property.description %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @property.code %>
</p>

<p>
  <strong>Value:</strong>
  <%= @property.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>